### ISSUE TITLE
Sortable Column

### ISSUE THREAD

**Issue by mike-aungsan** [gchatelet/GwtResizableDraggableColumns#1]
The only perfect solution out there for resizable column and its header. But when using this ResizableHeader class, column cannot sort anymore.

The following does not work. With or without the first line.

idColumn.setSortable(true);

TableCellResizableHeader<TestResultSummary> idTableCellResizableHeader = new TableCellResizableHeader<TestResultSummary>("Id", this.table, idColumn);

idTableCellResizableHeader.getColumn().setSortable(true);

table.addColumn(idTableCellResizableHeader.getColumn(), idTableCellResizableHeader);

The following work. 

table.addColumn(idColumn, "Id");
idColumn.setSortable(true);

**Comment by gchatelet** [comment]
Thx for reporting. I'll try to fix that whenever I can : ) Feel free to contribute a patch if you feel like it.

**Comment by puthali** [comment]
I fixed this sorting issue when I used it in my code. I'll try to upload a patch soon.

**Comment by mike-aungsan** [comment]
There are more issue I found. First of all, I try to add Minimum column
size and Max column size. I will send you the code. I do not have much
experience with DOM yet. So it might not be perfect.

When dragging column, only the first 4 or 5 columns show dragging lines.
The rest of the column does not show the line.

There are lots of feature that I would like to add similar to
_google_-web-toolkit-_incubator_http://code.google.com/p/google-web-toolkit-incubator/
 example such as header color, table border color and etc...

But some of them, I do not even know where to start. If you have a good ref
or doc of how to, share with me please.

Thanks puthali.

**Comment by gchatelet** [comment]
Thx @puthali for the patch. I integrated it and did a bit of refactoring.

Also the example now displays a CellTable and a DataGrid at the same time. This demonstrate a bug with the placement of the headers for the CellTable ( I'll create a new issue for that )

It is now possible to sort columns so I will close this issue.

@mike-aungsan can you fill in some more issues for the bugs you discovered ?

Also, at some point, it'll be a good idea to merge this project within google-web-toolkit-incubator but for now I think it needs some more work. I'm not quite happy with the design and there are still some bugs showing up from time to time.
